# Generated by Django 6.0.1 on 2026-01-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.O')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('purchased_book_ids', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Profile_',
            },
        ),
    ]
