# Generated by Django 6.0.1 on 2026-01-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Kitob nomi')),
                ('title', models.CharField(max_length=255, verbose_name='Kitob haqida')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('author_id', models.PositiveIntegerField()),
                ('category_id', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Kitoblar_',
            },
        ),
    ]
